info:
  contact: {}
paths:
  /generate_keys:
    post:
      consumes:
      - application/json
      description: generat a pair of keys
      produces:
      - application/json
      responses:
        "200":
          description: keys_generated
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "404":
          description: not_found
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      tags:
      - User operations
  /upload_file:
    post:
      consumes:
      - multipart/form-data
      description: upload a file to encrypt
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: file_uploaded
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "404":
          description: not_found
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      tags:
      - User operations
swagger: "2.0"
