basePath: /
definitions:
  handler.StringData:
    properties:
      data:
        type: string
    type: object
info:
  contact: {}
  description: Agent Operations
  title: Agent API
  version: 1.0.0
paths:
  /encryption/decrypt_file:
    post:
      consumes:
      - multipart/form-data
      description: Decrypt a file
      parameters:
      - description: Filename
        in: query
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: file_decrypted
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Decrypt file
      tags:
      - Encryption
  /encryption/generate_keys:
    post:
      consumes:
      - application/json
      description: Generate a pair of keys
      produces:
      - application/json
      responses:
        "200":
          description: keys_generated
          schema:
            type: string
        "500":
          description: internal_server_rror
          schema:
            type: string
      summary: Generate keys
      tags:
      - Encryption
  /encryption/save_file:
    post:
      consumes:
      - multipart/form-data
      description: Save file
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: file_saved
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "404":
          description: not_found
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Save file
      tags:
      - File
  /encryption/size_and_decrypt:
    post:
      consumes:
      - application/json
      description: Get size and decrypt
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.StringData'
      produces:
      - application/json
      responses:
        "200":
          description: file_decrypted
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "404":
          description: not_found
          schema:
            type: string
        "500":
          description: internal_server_error
          schema:
            type: string
      summary: Get size and decrypt
      tags:
      - Encryption
  /encryption/upload_encrypted_file:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: file_uploaded
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_rror
          schema:
            type: string
      summary: Upload encrypted file
      tags:
      - Encryption
  /encryption/upload_file:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file to encrypt
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: file_uploaded
          schema:
            type: string
        "400":
          description: bad_request
          schema:
            type: string
        "500":
          description: internal_server_rror
          schema:
            type: string
      summary: Upload file
      tags:
      - Encryption
swagger: "2.0"
