info:
  contact: {}
paths:
  /decrypt_file:
    post:
      consumes:
      - application/json
      description: decrypt an encrypted file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - User operations
  /generate_keys:
    post:
      consumes:
      - application/json
      description: generat a pair of keys
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - User operations
  /upload_file:
    post:
      consumes:
      - application/json
      description: upload a file to encrypt
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - User operations
swagger: "2.0"
